// <auto-generated />
namespace mukatalev1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291701559_adding date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
